export default {
  blocks: [
    {
      key: "tbl01",
      text: "Table support demo",
      type: "header-two",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "54qpo",
      text: "Hello, World!",
      type: "table-cell",
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 7,
          length: 5,
          style: "BOLD",
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: "ci9rr",
      text: "",
      type: "table-cell",
      depth: 1,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "a0781",
      text: "",
      type: "table-cell",
      depth: 100,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "bv3e3",
      text: "This is an example of a table",
      type: "table-cell",
      depth: 101,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "dc2in",
      text: "",
      type: "table-cell",
      depth: 200,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "a6pf1",
      text: "It kind of works",
      type: "table-cell",
      depth: 201,
      inlineStyleRanges: [
        {
          offset: 3,
          length: 7,
          style: "BOLD",
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: "tbl02",
      text: "Some text between tables.",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "tbl03",
      text: "Name",
      type: "table-cell",
      depth: 0,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 4,
          style: "BOLD",
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: "tbl04",
      text: "Role",
      type: "table-cell",
      depth: 1,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 4,
          style: "BOLD",
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: "tbl05",
      text: "Status",
      type: "table-cell",
      depth: 2,
      inlineStyleRanges: [
        {
          offset: 0,
          length: 6,
          style: "BOLD",
        },
      ],
      entityRanges: [],
      data: {},
    },
    {
      key: "tbl06",
      text: "Alice",
      type: "table-cell",
      depth: 100,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "tbl07",
      text: "Engineer",
      type: "table-cell",
      depth: 101,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "tbl08",
      text: "Active",
      type: "table-cell",
      depth: 102,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
  ],
  entityMap: {},
};
